// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('game29App').controller('PlayCtrl', function($scope, $http, socket) {
    var changeName;
    $scope.roomName = 'default';
    $scope.messages = [
      {
        user: 'test1',
        text: 'message1'
      }, {
        user: 'test2',
        text: 'message2'
      }
    ];
    $http.get('/api/awesomeThings').success(function(awesomeThings) {
      return $scope.awesomeThings = awesomeThings;
    });
    socket.on('init', function(data) {
      $scope.name = data.name;
      return $scope.users = data.users;
    });
    socket.on('send:message', function(message) {
      return $scope.messages.push(message);
    });
    socket.on('change:name', function(data) {
      return changeName(data.oldName, data.newName);
    });
    socket.on('user:join', function(data) {
      $scope.messages.push({
        user: 'chatroom',
        text: "User " + data.name + " has joined."
      });
      return $scope.users.push(data.name);
    });
    socket.on('user:left', function(data) {
      var i, user, _i, _len, _ref;
      $scope.messages.push({
        user: 'chatroom',
        text: "User " + data.name + " has left."
      });
      _ref = $scope.users;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        user = _ref[i];
        if (user === data.name) {
          $scope.users.splice(i, 1);
          break;
        }
      }
    });
    changeName = function(oldName, newName) {
      var user, _i, _len, _ref;
      _ref = $scope.users;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        user = _ref[_i];
        if (user === oldName) {
          user = newName;
          break;
        }
      }
      return $scope.messages.push({
        user: 'chatroom',
        text: "User " + oldName + " is now known as " + newName + "."
      });
    };
    $scope.changeName = function() {
      return socket.emit("change:name", {
        name: $scope.newName
      }, function(result) {
        if (!result) {
          return alert("There was an error changing your name");
        } else {
          changeName($scope.name, $scope.newName);
          $scope.name = $scope.newName;
          return $scope.newName = "";
        }
      });
    };
    return $scope.sendMessage = function() {
      socket.emit("send:message", {
        message: $scope.message
      });
      $scope.messages.push({
        user: $scope.name,
        text: $scope.message
      });
      return $scope.message = "";
    };
  });

}).call(this);

/*
//@ sourceMappingURL=play.map
*/
