// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('game29App').controller('PlayCtrl', function($scope, $http, socket) {
    var changeName, changeRoom;
    $scope.room = '';
    $scope.rooms = ['room1', 'room2'];
    $scope.messages = [
      {
        user: 'test1',
        text: 'message1'
      }, {
        user: 'test2',
        text: 'message2'
      }
    ];
    $http.get('/api/awesomeThings').success(function(awesomeThings) {
      return $scope.awesomeThings = awesomeThings;
    });
    socket.on('init', function(data) {
      $scope.name = data.name;
      $scope.users = data.users;
      return $scope.rooms = data.rooms;
    });
    socket.on('send:message', function(message) {
      return $scope.messages.push(message);
    });
    socket.on('change:name', function(data) {
      return changeName(data.oldName, data.newName);
    });
    socket.on('change:room', function(data) {
      $scope.room = data.room;
      $scope.users = data.users;
      return $scope.rooms = data.rooms;
    });
    socket.on('user:join', function(data) {
      $scope.messages.push({
        user: 'chatroom',
        text: "User " + data.name + " has joined."
      });
      return $scope.users.push(data.name);
    });
    socket.on('user:left', function(data) {
      $scope.messages.push({
        user: 'chatroom',
        text: "User " + data.name + " has left."
      });
      return _.remove($scope.users, function(user) {
        return user === data.name;
      });
    });
    changeName = function(oldName, newName) {
      var index, user, _i, _len, _ref;
      _ref = $scope.users;
      for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
        user = _ref[index];
        if (user === oldName) {
          $scope.users[index] = newName;
          break;
        }
      }
      return $scope.messages.push({
        user: 'chatroom',
        text: "User " + oldName + " is now known as " + newName + "."
      });
    };
    changeRoom = function(oldRoom, newRoom, newUsers) {
      $scope.messages.length = 0;
      $scope.messages.push({
        user: 'chatroom',
        text: "Changing room from " + oldRoom + " to " + newRoom + "."
      });
      $scope.name = $scope.newRoom;
      $scope.newRoom = "";
      return $scope.users = newUsers;
    };
    $scope.changeName = function() {
      return socket.emit("change:name", {
        name: $scope.newName
      }, function(result) {
        if (!result) {
          return alert("There was an error changing your name");
        } else {
          changeName($scope.name, $scope.newName);
          $scope.name = $scope.newName;
          return $scope.newName = "";
        }
      });
    };
    $scope.sendMessage = function() {
      socket.emit("send:message", {
        message: $scope.message
      });
      $scope.messages.push({
        user: $scope.name,
        text: $scope.message
      });
      return $scope.message = "";
    };
    return $scope.changeRoom = function() {
      console.log("sending change:room to server");
      return socket.emit("change:room", {
        room: $scope.newRoom
      }, function(result) {
        console.log("recieved change:room response from server");
        if (!result) {
          return alert("There was an error changing your room");
        } else {
          return changeRoom($scope.room, result.users);
        }
      });
    };
  });

}).call(this);

/*
//@ sourceMappingURL=play.map
*/
