// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: PlayCtrl', function() {
    var $httpBackend, PlayCtrl, scope;
    beforeEach(module('game29App'));
    PlayCtrl = {};
    scope = {};
    $httpBackend = {};
    beforeEach(inject(function(_$httpBackend_, $controller, $rootScope) {
      $httpBackend = _$httpBackend_;
      $httpBackend.expectGET('/api/awesomeThings').respond(['HTML5 Boilerplate', 'AngularJS', 'Karma', 'Express']);
      scope = $rootScope.$new();
      return PlayCtrl = $controller('PlayCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      expect(scope.awesomeThings).to.be.undefined;
      $httpBackend.flush();
      return expect(scope.awesomeThings.length).to.be(4);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=play.map
*/
