// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('game29App').service('socket', function($rootScope) {
    var Socket;
    Socket = (function() {
      function Socket() {
        this.socket = io.connect();
      }

      Socket.prototype.on = function(eventName, callback) {
        return this.socket.on(eventName, function() {
          var args, socket;
          args = arguments;
          socket = this.socket;
          return $rootScope.$apply(function() {
            return callback.apply(socket, args);
          });
        });
      };

      Socket.prototype.emit = function(eventName, data, callback) {
        return this.socket.emit(eventName, data, function() {
          var args, socket;
          args = arguments;
          socket = this.socket;
          return $rootScope.$apply(function() {
            if (callback) {
              return callback.apply(socket, args);
            }
          });
        });
      };

      return Socket;

    })();
    return new Socket;
  });

}).call(this);

/*
//@ sourceMappingURL=socket.map
*/
