// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('game29App').service('Socket', function($rootScope) {
    var socket, socketEvents;
    socket = io.connect();
    return socketEvents = {
      on: function(eventName, callback) {
        socket.on(eventName, function() {
          var args;
          args = arguments;
          $rootScope.$apply(function() {
            return callback.apply(socket, args);
          });
        });
      },
      emit: function(eventName, data, callback) {
        socket.emit(eventName, data, function() {
          var args;
          args = arguments;
          $rootScope.$apply(function() {
            if (callback) {
              return callback.apply(socket, args);
            }
          });
        });
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=socket.map
*/
